### ISSUE TITLE
Build fails (with no extra info)

### ISSUE THREAD

**Issue by stackotter** [tristanlabelle/swift-winui-sample#10]
I've been trying to build this sample in a Windows 11 ARM virtual machine cause I'm hoping to switch [SwiftCrossUI](https://github.com/stackotter/swift-cross-ui) over to your swift-winrt due to thebrowserco's swift-winui repository getting archived.

I would've given the issue a better name but the cmake build process hangs while printing the error message; I don't know what the nature of the issue is. The main thing I was hoping is that you might spot something wrong with the steps I've followed, or have some insight into debugging this issue.

The only thing that I've gotten out of the error message is that the command that failed refers to a lot of files in `Dependencies\WinRT\Build`, which doesn't exist.

### Rough reproduction steps

I've tried a bunch of different stuff so I've probably missed some parts of my env, but hopefully there's still enough info to be useful.

- Start with a fresh
- Install Swift 6.0.2 using the latest WinGet-based instructions from swift.org
- `winget install -e --id Kitware.CMake`
- `winget install -e --id Ninja-build.Ninja`
- `winget install -e --id Microsoft.NuGet`
- In a local `swift-winrt` checkout
  - `cmake --preset debug -D CMAKE_EXPORT_COMPILE_COMMANDS=OFF`
  - `powershell Generator\NuGet\Create-Package.ps1 -NativeExe build\debug\Generator\SwiftWinRT.exe -Version 0.0.0 -OutputPath .\TristanLabelle.SwiftWinRT.0.0.0.nupkg`
- In a local `swift-winui-sample` checkout next to `swift-winrt`
  - `cp ..\swift-winrt\TristanLabelle.SwiftWinRT.0.0.0.nupkg Dependencies\NuGet\Overrides`
  - `New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force`
  - Add `set(CMAKE_OBJECT_PATH_MAX 1024)` to `CMakeLists.txt` (after line 5)
    - I was getting an error about an object file's path being too long (something produced for Windows Foundation I think?)
  - Replace first line of `Dependencies/WinRT/CMakeLists.txt` with the following block;
    ```cmake
    if(EXISTS "${TristanLabelle.SwiftWinRT_NUGET_PACKAGE_DIR}/tools/x64")
        set(SWIFTWINRT_EXE "${TristanLabelle.SwiftWinRT_NUGET_PACKAGE_DIR}/tools/x64/SwiftWinRT.exe")
    else()
        set(SWIFTWINRT_EXE "${TristanLabelle.SwiftWinRT_NUGET_PACKAGE_DIR}/tools/ARM64/SwiftWinRT.exe")
    endif()
    ```
  - `cmake --preset debug -D CMAKE_EXPORT_COMPILE_COMMANDS=OFF`
  - `cmake --build --preset debug` (**this is what fails**)

### Log from final build command

The error message consistently gets cut off at the same character, and the build process always just hangs instead of exiting. This means that the error message is basically useless cause it only prints out the first part of the command that failed. Not sure why it does that.

```
PS C:\Users\stackotter\Documents\swift-winui-sample> cmake --build --preset debug
[49/67] Linking Swift static library Dependencies\WinRT\Build\WindowsAppSDK\Namespaces\Flat\WindowsAppSDK_Flat.lib
FAILED: Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/Flat/WindowsAppSDK_Flat.lib Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/Flat/CMakeFiles/WindowsAppSDK_Flat.dir/Flat.swift.obj Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/Flat/WindowsAppSDK_Flat.swiftmodule
C:\WINDOWS\system32\cmd.exe /C "cd . && C:\Users\stackotter\AppData\Local\Programs\Swift\Toolchains\6.0.2+Asserts\usr\bin\swiftc.exe -j 4 -num-threads 4 -emit-library -static -o Dependencies\WinRT\Build\WindowsAppSDK\Namespaces\Flat\WindowsAppSDK_Flat.lib -module-name WindowsAppSDK_Flat -module-link-name WindowsAppSDK_Flat -emit-module -emit-module-path Dependencies\WinRT\Build\WindowsAppSDK\Namespaces\Flat\WindowsAppSDK_Flat.swiftmodule -emit-dependencies  -DDEBUG -Onone -Xfrontend -g -Xfrontend -debug-info-format=dwarf -use-ld=lld -Xlinker -debug:dwarf -libc MDd -driver-filelist-threshold=2147483647 -output-file-map Dependencies\WinRT\Build\WindowsAppSDK\Namespaces\Flat\CMakeFiles\WindowsAppSDK_Flat.dir\Debug\output-file-map.json -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Support/WindowsRuntime -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Support/COM -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUI -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Projection -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIComposition -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUICompositionSystemBackdrops -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIContent -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIDispatching -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIInput -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIWindowing -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftWindowsApplicationModelResources -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Support/ABIBindings -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/NuGet/TristanLabelle.SwiftWinRT.0.0.0/swift/COM_ABI/include -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/NuGet/TristanLabelle.SwiftWinRT.0.0.0/swift/WindowsRuntime_ABI/include -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Sources/WindowsAppSDK/ABI/include -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Sources/UWP/ABI/include C:\Users\
```

**Comment by tristanlabelle** [comment]
Hi @stackotter !

> I'm hoping to switch [SwiftCrossUI](https://github.com/stackotter/swift-cross-ui) over to your swift-winrt due to thebrowserco's swift-winui repository getting archived.

The `thebrowsercompany/swift-winui` archival doesn't impact the health of `thebrowsercompany/swift-winrt`, it's just a recognition that we weren't keeping the pregenerated repos updated, and that there is no way to keep them updated in a way that would work for all of its consumers. You can still use `thebrowsercompany/swift-winrt` to generate your projections, and it is a more battle-tested project than `tristanlabelle/swift-winrt`.

That said, I'm impressed with how far you got here since I'm still in local iteration mode and haven't gotten to making these repos very easy to use. I haven't tested arm64 myself and don't have a machine available to do so. I have observed that initial projection builds take a long time (10-15 mins?) but they haven't completely frozen on me. However at that time I didn't have the `_Flat` modules yet and I do expect them to run into poor compiler perf. The only idea I have is to use `ninja -C build/debug --verbose WindowsAppSDK_Flat` to try to get more info on where the build is hanging. But do give it many minutes before giving up.

I've also kept iterating on `swift-winrt` and may need to update `swift-winui-sample` based on recent changes to the former.

Next on my list is to produce a new "official" release of swift-winrt and hook up `swift-winui-sample` to download it from GitHub to streamline the process a little.

**Comment by stackotter** [comment]
> The `thebrowsercompany/swift-winui` archival doesn't impact the health of `thebrowsercompany/swift-winrt`, it's just a recognition that we weren't keeping the pregenerated repos updated, and that there is no way to keep them updated in a way that would work for all of its consumers. You can still use `thebrowsercompany/swift-winrt` to generate your projections, and it is a more battle-tested project than `tristanlabelle/swift-winrt`.

I decided that if I was switching to self generation I might as well try out your Swift-based one, but that was before I realised that this was still in its early stages. It looks like you've made plenty of progress regardless! (i.e. enough for me to like the look of your project more than the C++ one)

I guess for now I'll just stick to the C++ generator and keep an eye on this repo.

> I have observed that initial projection builds take a long time (10-15 mins?) but they haven't completely frozen on me.

Yeah some steps took quite a while, but this one did print out an error so I'm assuming it did actually fail + hang (I left it for quite a while and it never printed out any more of the error message).

> Next on my list is to produce a new "official" release of swift-winrt and hook up swift-winui-sample to download it from GitHub to streamline the process a little.

Sounds good! One thing I ran into was that when a `nupkg` doesn't contain anything for the current architecture, NuGet just pretends that it can't find the package at all (instead of saying that it found a matching package but not one with the right architecture). That took me quite a while to figure out because I haven't used NuGet before and so I assumed that I had just placed the downloaded `nupkg` at the wrong location.

**Comment by stackotter** [comment]
> The only idea I have is to use `ninja -C build/debug --verbose WindowsAppSDK_Flat` to try to get more info on where the build is hanging.

Thanks that was very helpful! It printed the entire error message and exited immediately. The error seems to be `missing required module 'UWP'`.

```
PS C:\Users\stackotter\Documents\swift-winui-sample> ninja -C build/debug --verbose WindowsAppSDK_Flat
ninja: Entering directory `build/debug'
[1/1] C:\WINDOWS\system32\cmd.exe /C "cd . && C:\Users\stackotter\AppData\Local\Programs\Swift\Toolchains\6.0.2+Asserts\usr\bin\swiftc.exe -j 4 -num-threads 4 -emit-library -static -o Dependencies\WinRT\Build\WindowsAppSDK\Namespaces\Flat\WindowsAppSDK_Flat.lib -module-name WindowsAppSDK_Flat -module-link-name WindowsAppSDK_Flat -emit-module -emit-module-path Dependencies\WinRT\Build\WindowsAppSDK\Namespaces\Flat\WindowsAppSDK_Flat.swiftmodule -emit-dependencies  -DDEBUG -Onone -Xfrontend -g -Xfrontend -debug-info-format=dwarf -use-ld=lld -Xlinker -debug:dwarf -libc MDd -driver-filelist-threshold=2147483647 -output-file-map Dependencies\WinRT\Build\WindowsAppSDK\Namespaces\Flat\CMakeFiles\WindowsAppSDK_Flat.dir\Debug\output-file-map.json -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Support/WindowsRuntime -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Support/COM -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUI -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Projection -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIComposition -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUICompositionSystemBackdrops -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIContent -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIDispatching -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIInput -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIWindowing -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftWindowsApplicationModelResources -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Support/ABIBindings -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/NuGet/TristanLabelle.SwiftWinRT.0.0.0/swift/COM_ABI/include -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/NuGet/TristanLabelle.SwiftWinRT.0.0.0/swift/WindowsRuntime_ABI/include -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Sources/WindowsAppSDK/ABI/include -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Sources/UWP/ABI/include C:\Users\stackotter\Documents\swift-winui-sample\build\debug\Dependencies\WinRT\Sources\WindowsAppSDK\Namespaces\Flat\Flat.swift    && cd ."
FAILED: Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/Flat/WindowsAppSDK_Flat.lib Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/Flat/CMakeFiles/WindowsAppSDK_Flat.dir/Flat.swift.obj Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/Flat/WindowsAppSDK_Flat.swiftmodule
C:\WINDOWS\system32\cmd.exe /C "cd . && C:\Users\stackotter\AppData\Local\Programs\Swift\Toolchains\6.0.2+Asserts\usr\bin\swiftc.exe -j 4 -num-threads 4 -emit-library -static -o Dependencies\WinRT\Build\WindowsAppSDK\Namespaces\Flat\WindowsAppSDK_Flat.lib -module-name WindowsAppSDK_Flat -module-link-name WindowsAppSDK_Flat -emit-module -emit-module-path Dependencies\WinRT\Build\WindowsAppSDK\Namespaces\Flat\WindowsAppSDK_Flat.swiftmodule -emit-dependencies  -DDEBUG -Onone -Xfrontend -g -Xfrontend -debug-info-format=dwarf -use-ld=lld -Xlinker -debug:dwarf -libc MDd -driver-filelist-threshold=2147483647 -output-file-map Dependencies\WinRT\Build\WindowsAppSDK\Namespaces\Flat\CMakeFiles\WindowsAppSDK_Flat.dir\Debug\output-file-map.json -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Support/WindowsRuntime -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Support/COM -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUI -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Projection -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIComposition -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUICompositionSystemBackdrops -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIContent -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIDispatching -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIInput -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftUIWindowing -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Build/WindowsAppSDK/Namespaces/MicrosoftWindowsApplicationModelResources -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Support/ABIBindings -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/NuGet/TristanLabelle.SwiftWinRT.0.0.0/swift/COM_ABI/include -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/NuGet/TristanLabelle.SwiftWinRT.0.0.0/swift/WindowsRuntime_ABI/include -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Sources/WindowsAppSDK/ABI/include -I C:/Users/stackotter/Documents/swift-winui-sample/build/debug/Dependencies/WinRT/Sources/UWP/ABI/include C:\Users\stackotter\Documents\swift-winui-sample\build\debug\Dependencies\WinRT\Sources\WindowsAppSDK\Namespaces\Flat\Flat.swift    && cd ."
<unknown>:0: error: missing required module 'UWP'
error: emit-module command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: missing required module 'UWP'
ninja: build stopped: subcommand failed.
PS C:\Users\stackotter\Documents\swift-winui-sample>
```

**Comment by tristanlabelle** [comment]
Ah interesting, thanks for that! The project doesn't actually use the `_Flat` modules yet so if you build with `cmake --build --preset debug --target Sample` or `ninja -C build\debug Sample`, it will build only the modules that are actually referenced and will skip that one.

> I guess for now I'll just stick to the C++ generator and keep an eye on this repo.

That's wise. This project is getting close but still experimental enough that I'm not comfortable with recommending it or blessing it with a 1.0 version number. Even if you get past building it, there are still crashes that I'm ironing out.

> Sounds good! One thing I ran into was that when a nupkg doesn't contain anything for the current architecture, NuGet just pretends that it can't find the package at all (instead of saying that it found a matching package but not one with the right architecture). That took me quite a while to figure out because I haven't used NuGet before and so I assumed that I had just placed the downloaded nupkg at the wrong location.

In my mental model, NuGet doesn't care what's inside the package, including the architecture. Is it possible that the issue was that the CMake code is hard-coded to look for an x64 directory?

**Comment by tristanlabelle** [comment]
I promoted your build error issue to https://github.com/tristanlabelle/swift-winrt/issues/456 and will close this (but feel free to keep discussing).

**Comment by stackotter** [comment]
> Ah interesting, thanks for that! The project doesn't actually use the _Flat modules yet so if you build with cmake --build --preset debug --target Sample or ninja -C build\debug Sample, it will build only the modules that are actually referenced and will skip that one.

That worked! (with some minor changes to `SwiftApplication.swift` to fix some `COMImplements` related compilation errors)

However, when I run `Sample.exe`, the compiled exe just exits immediately with exit code `0` and no warnings or error messages. I've been having exactly the same issue with `thebrowserco/swift-winui`, which is the whole reason I started looking around for alternative bindings.

I'm assuming that it's probably some sort of environment set up issue on my end. Is there something obvious I have to install to get WinUI apps working correctly? I've really only installed the stuff I listed in the original issue description and the SDK that `thebrowserco`'s Swift WinRT stuff requires.

**Comment by stackotter** [comment]
> In my mental model, NuGet doesn't care what's inside the package, including the architecture. Is it possible that the issue was that the CMake code is hard-coded to look for an x64 directory?

Yeah I don't have a mental model of NuGet at all (or Windows for that matter) so it's probably best for me to just document the steps I took and the error message so that you can do your own analysis. All of this is in a Windows 11 ARM64 VM of course.

1. Clone `tristanlabelle/swift-winui-sample`
2. Download `SwiftWinRT.nupkg` from GitHub actions
3. Move the `nupkg` to `swift-winui-sample/Dependencies/NuGet/Overrides/TristanLabelle.SwiftWinRT.0.0.0.nupkg`
4. `cmake --preset debug -D CMAKE_EXPORT_COMPILE_COMMANDS=OFF`

The last step fails with this error (I've omitted the successful but unrelated compiler check logs);

```
-- Restoring NuGet packages...
Unable to find version '0.0.0' of package 'TristanLabelle.SwiftWinRT'.
  C:\Users\stackotter\.nuget\packages\: Package 'TristanLabelle.SwiftWinRT.0.0.0' is not found on source 'C:\Users\stackotter\.nuget\packages\'.
  C:\Users\stackotter\Documents\winui-sample-2\Dependencies\NuGet\Overrides: Package 'TristanLabelle.SwiftWinRT.0.0.0' is not found on source 'C:\Users\stackotter\Documents\winui-sample-2\Dependencies\NuGet\Overrides'.
  https://api.nuget.org/v3/index.json: Package 'TristanLabelle.SwiftWinRT.0.0.0' is not found on source 'https://api.nuget.org/v3/index.json'.

Errors in packages.config projects
    Unable to find version '0.0.0' of package 'TristanLabelle.SwiftWinRT'.
      C:\Users\stackotter\.nuget\packages\: Package 'TristanLabelle.SwiftWinRT.0.0.0' is not found on source 'C:\Users\stackotter\.nuget\packages\'.
      C:\Users\stackotter\Documents\winui-sample-2\Dependencies\NuGet\Overrides: Package 'TristanLabelle.SwiftWinRT.0.0.0' is not found on source 'C:\Users\stackotter\Documents\winui-sample-2\Dependencies\NuGet\Overrides'.
      https://api.nuget.org/v3/index.json: Package 'TristanLabelle.SwiftWinRT.0.0.0' is not found on source 'https://api.nuget.org/v3/index.json'.
    Unable to find version '0.0.0' of package 'TristanLabelle.SwiftWinRT'.
      C:\Users\stackotter\.nuget\packages\: Package 'TristanLabelle.SwiftWinRT.0.0.0' is not found on source 'C:\Users\stackotter\.nuget\packages\'.
      C:\Users\stackotter\Documents\winui-sample-2\Dependencies\NuGet\Overrides: Package 'TristanLabelle.SwiftWinRT.0.0.0' is not found on source 'C:\Users\stackotter\Documents\winui-sample-2\Dependencies\NuGet\Overrides'.
      https://api.nuget.org/v3/index.json: Package 'TristanLabelle.SwiftWinRT.0.0.0' is not found on source 'https://api.nuget.org/v3/index.json'.
CMake Error at Dependencies/NuGet/CMakeLists.txt:7 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"



-- Configuring incomplete, errors occurred!
```

If I replace the `nupkg` with one built locally, the `Restoring NuGet packages...` step succeeds and the build fails at the next step due to the hardcoded `x64` in the path (which I've fixed in my local copy).

It seems like the original failure is within NuGet and isn't related to the hardcoded path.

**Comment by stackotter** [comment]
> However, when I run Sample.exe, the compiled exe just exits immediately with exit code 0 and no warnings or error messages. I've been having exactly the same issue with thebrowserco/swift-winui, which is the whole reason I started looking around for alternative bindings.

Looking into this some more, I found that `Sample.exe` was getting linked against x64 versions of the Windows App Runtime related dlls, but after fixing that it still exhibits the same behaviour.

**Comment by tristanlabelle** [comment]
> Download SwiftWinRT.nupkg from GitHub actions

You still need to build your own `SwiftWinRT.nupkg`, the version in the releases is very old at this point.

> That worked! (with some minor changes to SwiftApplication.swift to fix some COMImplements related compilation errors)

I've pushed some changes to this repo to update the use of `COMImplements` to the latest API shape (it's still a moving target as I iterate).

> However, when I run Sample.exe, the compiled exe just exits immediately with exit code 0 and no warnings or error messages. I've been having exactly the same issue with thebrowserco/swift-winui, which is the whole reason I started looking around for alternative bindings.

The exit code zero is puzzling. I was expecting you'd hit a crash from the IXamlMetadataProvider stuff which I'm still working on figuring out. You can workaround it by removing the queryInterface overload in SwiftApplication, but at the cost of losing the default XAML theming.

If you look under the `build\debug\Dependencies\NuGet` folder, you should find the msix'es to install the Windows App Runtime version that this project uses. Can you install them and see if you hit the same issue? Normally a dialog should show if the required version is not installed, with a link to go install it.

> Looking into this some more, I found that Sample.exe was getting linked against x64 versions of the Windows App Runtime related dlls, but after fixing that it still exhibits the same behaviour.

Oh that makes sense. Can you double-check that all dll's and exe's under `build\debug\Sources` are arm64?

```
D:\swift-winui-sample\build\debug\Sources>dumpbin /headers UWP.dll | findstr "machine"
            8664 machine (x64)

 :\swift-winui-sample\build\debug\Sources>dumpbin /headers Microsoft.WindowsAppRuntime.Bootstrap.dll | findstr "machine"
            8664 machine (x64)

D:\swift-winui-sample\build\debug\Sources>dumpbin /headers WindowsAppSDK.dll | findstr "machine"
            8664 machine (x64)

D:\swift-winui-sample\build\debug\Sources>dumpbin /headers WinUI.dll | findstr "machine"
            8664 machine (x64)

D:\swift-winui-sample\build\debug\Sources>dumpbin /headers Sample.exe | findstr "machine"
            8664 machine (x64)

**Comment by tristanlabelle** [comment]
And you got this error:

```
Unable to find version '0.0.0' of package 'TristanLabelle.SwiftWinRT'.
  C:\Users\stackotter\.nuget\packages\: Package 'TristanLabelle.SwiftWinRT.0.0.0' is not found on source 'C:\Users\stackotter\.nuget\packages\'.
  C:\Users\stackotter\Documents\winui-sample-2\Dependencies\NuGet\Overrides: Package 'TristanLabelle.SwiftWinRT.0.0.0' is not found on source 'C:\Users\stackotter\Documents\winui-sample-2\Dependencies\NuGet\Overrides'.
  https://api.nuget.org/v3/index.json: Package 'TristanLabelle.SwiftWinRT.0.0.0' is not found on source 'https://api.nuget.org/v3/index.json'.
```

When there existed a file called `C:\Users\stackotter\Documents\winui-sample-2\Dependencies\NuGet\Overrides\TristanLabelle.SwiftWinRT.0.0.0.nupkg`? That is indeed a nuget error, not an error in the surrounding CMake logic.

Can you try deleting `packages.lock.json`? (or pull the latest main)

**Comment by stackotter** [comment]
> The exit code zero is puzzling. I was expecting you'd hit a crash from the IXamlMetadataProvider stuff which I'm still working on figuring out. You can workaround it by removing the queryInterface overload in SwiftApplication, but at the cost of losing the default XAML theming.

I've tried removing that now and still got the same behaviour.

I did a bit more digging and I've found that the exit is occurring before `SampleApplication.main` even gets called, so it definitely smells like an environment/runtime/dll kinda issue. I replaced it with a print statement followed immediately by `Foundation.exit(1)` and still got a zero exit code with no output (and I've confirmed that the recompilation is actually happening).

I've found that if I remove the `SUBSYSTEM:WINDOWS` linker flag, change the entry point flag to `entry:main`, and comment out `SampleApplication` and `SwiftApplication`, replacing them with a custom `@main` entrypoint that just prints hello world, then it finally works (i.e. runs any swift code at all).

If I uncomment the `SwiftApplication` implementation with those linker flag changes still in place I get;

```
lld-link: error: msvcrt.lib(chkstk.obj): machine type x86 conflicts with arm64
```

Ok actually, now I've reverted the changes one-by-one (trying to figure out which were necessary and which weren't) and the linker architecture issue is persisting, so who knows what's going on there 😭 It's quite late here now so I'll finish off the rest of my reply and revisit things tomorrow when I have time to wait for full rebuilds and stuff (a full rebuild seems to take 40 minutes with my current VM configuration... and most of that time is just linking two dlls).

> Oh that makes sense. Can you double-check that all dll's and exe's under build\debug\Sources are arm64?

Yeah, they are with my local `CMakeLists.txt` changes that I mentioned somewhere above (but aren't with the main branch). When I had the initial incorrect architecture issues, the exe behaviour was almost identical (the only difference being that opening via File Explorer displayed an error dialog).

> When there existed a file called `C:\Users\stackotter\Documents\winui-sample-2\Dependencies\NuGet\Overrides\TristanLabelle.SwiftWinRT.0.0.0.nupkg`? That is indeed a nuget error, not an error in the surrounding CMake logic.
>
> Can you try deleting `packages.lock.json`? (or pull the latest main)

Yeah I've tried deleting `packages.lock.json`.

When I reproduced the issue, I performed one build with the downloaded nupkg (which failed with that error message you emphasised) and then replaced the downloaded nupkg with a locally built one (of the same name) and performed another build (which succeeded).

---

Something interesting about this silent failure issue is that my mouse cursor displays a spinner for a second or two after the exe exits. In this case I don't really know what that indicates, but it seems a little out of the ordinary.

**Comment by stackotter** [comment]
> `lld-link: error: msvcrt.lib(chkstk.obj): machine type x86 conflicts with arm64`

The error disappeared when I started using `ARM64 Native Tools Command Prompt for VS 2022` instead of `Developer PowerShell for VS 2022`. It's strange that the issue persisted across all my projects once it started, but at least I found a fix.

---

I've finally gotten a sample app working with `thebrowserco/swift-winui`, which was exhibiting the same issues as this sample! The issue there was that the bootstrap dll (included as a resource in the `thebrowserco/swift-windowsappsdk` repository) was an x64 dll. I had checked for basically that exact issue, but since thebrowserco's bindings load the dll by path at runtime instead of linking against it at compile time, the tool I was using to find dependencies didn't list it.

I've double checked and this sample app's bootstrap dll is an ARM64 one (with my local changes). It is suspicious that the other sample was displaying identical behaviour though. Perhaps there's a sneaky dependency somewhere that I've missed?

**Comment by tristanlabelle** [comment]
Maybe you're using the correct bootstrap dll but still linking against the incorrect import library? If so, this will help: https://github.com/tristanlabelle/swift-winui-sample/pull/13

Also, out of curiosity, what are the values of `VSCMD_ARG_HOST_ARCH` and `VSCMD_ARG_TGT_ARCH` in your `Developer PowerShell for VS 2022`? I would have assumed they be the same as `ARM64 Native Tools Command Prompt for VS 2022`, aka both arm64.

**Comment by stackotter** [comment]
Ah that'll do it, `VSCMD_ARG_HOST_ARCH` is `x64` for `Developer PowerShell for VS 2022` 🤯 (while `VSCMD_ARG_TGT_ARCH` is `arm64`)

Just as a sanity check, `VSCMD_ARG_HOST_ARCH` is `arm64` for the `ARM64 Native Tools Command Prompt for VS 2022` as you'd expect.
